// Dummy data for UI preview

export const dummyUser = {
  id: 1,
  name: "Melos Kuqi",
  email: "melos@sonnix.com",
  balance: 125.50,
  tokens: 125,
};

export const dummyTransactions = [
  {
    id: 1,
    type: "Add Funds",
    amount: 50.00,
    description: "Added funds via Credit Card",
    date: "2024-11-10",
    status: "completed",
    isPositive: true,
  },
  {
    id: 2,
    type: "Purchase",
    amount: -15.00,
    description: "Event Ticket - Night Vibes 2024",
    date: "2024-11-09",
    status: "completed",
    isPositive: false,
  },
  {
    id: 3,
    type: "Refund",
    amount: 20.00,
    description: "Refund for cancelled event",
    date: "2024-11-08",
    status: "completed",
    isPositive: true,
  },
  {
    id: 4,
    type: "Sent",
    amount: -10.00,
    description: "Sent to @john_doe",
    date: "2024-11-07",
    status: "completed",
    isPositive: false,
  },
  {
    id: 5,
    type: "Received",
    amount: 25.00,
    description: "Received from @sarah_smith",
    date: "2024-11-06",
    status: "completed",
    isPositive: true,
  },
  {
    id: 6,
    type: "Drink Purchase",
    amount: -5.50,
    description: "2x Mojito at Club Venue",
    date: "2024-11-05",
    status: "completed",
    isPositive: false,
  },
];

export const dummyEvents = [
  {
    id: 1,
    title: "Night Vibes 2024",
    date: "2024-12-15",
    time: "21:00",
    venue: "The Grand Arena",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800",
    price: 25,
    description: "Experience the ultimate night of electronic music with world-class DJs and stunning visuals. A night you won't forget!",
    category: "Music",
  },
  {
    id: 2,
    title: "Summer Festival",
    date: "2024-12-20",
    time: "14:00",
    venue: "Beach Park",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800",
    price: 35,
    description: "Join us for a day full of sunshine, music, and good vibes at the beach. Multiple stages with diverse artists.",
    category: "Festival",
  },
  {
    id: 3,
    title: "Jazz Night",
    date: "2024-12-18",
    time: "19:30",
    venue: "Blue Note Club",
    image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800",
    price: 15,
    description: "An intimate evening of smooth jazz featuring local and international artists in a cozy setting.",
    category: "Jazz",
  },
];

export const dummyTickets = [
  {
    id: 1,
    eventId: 1,
    eventTitle: "Night Vibes 2024",
    date: "2024-12-15",
    venue: "The Grand Arena",
    qrCode: "TICKET-NV2024-001",
    seatNumber: "A-42",
    purchaseDate: "2024-11-09",
  },
];

export const dummyMerch = [
  {
    id: 1,
    name: "Sonnix T-Shirt",
    price: 20,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
    description: "Official Sonnix branded t-shirt. 100% cotton, available in multiple sizes.",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 2,
    name: "Sonnix Hat",
    price: 15,
    image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400",
    description: "Stylish Sonnix cap with embroidered logo. One size fits all.",
    sizes: ["One Size"],
  },
];

export const dummyVendorItems = [
  // Cocktail Bar items
  {
    id: 1,
    name: "Mojito",
    price: 11,
    category: "Cocktails",
    image: "🍹",
  },
  {
    id: 2,
    name: "Margarita",
    price: 12,
    category: "Cocktails",
    image: "🍸",
  },
  {
    id: 3,
    name: "Craft Beer",
    price: 8,
    category: "Beer",
    image: "🍺",
  },
  {
    id: 4,
    name: "IPA Beer",
    price: 9,
    category: "Beer",
    image: "🍺",
  },
  {
    id: 5,
    name: "Red Wine",
    price: 10,
    category: "Wine",
    image: "🍷",
  },
  {
    id: 6,
    name: "White Wine",
    price: 10,
    category: "Wine",
    image: "🍷",
  },
  // Street Food Hub items
  {
    id: 7,
    name: "Classic Burger",
    price: 12,
    category: "Burgers",
    image: "🍔",
  },
  {
    id: 8,
    name: "Cheese Burger",
    price: 14,
    category: "Burgers",
    image: "🍔",
  },
  {
    id: 9,
    name: "Hot Dog",
    price: 8,
    category: "Hot Dogs",
    image: "🌭",
  },
  {
    id: 10,
    name: "Chili Dog",
    price: 9,
    category: "Hot Dogs",
    image: "🌭",
  },
  {
    id: 11,
    name: "French Fries",
    price: 5,
    category: "Fries",
    image: "🍟",
  },
  {
    id: 12,
    name: "Curly Fries",
    price: 6,
    category: "Fries",
    image: "🍟",
  },
  // Energy Zone items
  {
    id: 13,
    name: "Red Bull",
    price: 6,
    category: "Energy Drinks",
    image: "🥤",
  },
  {
    id: 14,
    name: "Monster Energy",
    price: 6,
    category: "Energy Drinks",
    image: "🥤",
  },
  {
    id: 15,
    name: "Coca Cola",
    price: 4,
    category: "Soft Drinks",
    image: "🥤",
  },
  {
    id: 16,
    name: "Sprite",
    price: 4,
    category: "Soft Drinks",
    image: "🥤",
  },
  // Pizza Paradise items
  {
    id: 17,
    name: "Pepperoni Pizza",
    price: 15,
    category: "Pizza",
    image: "🍕",
  },
  {
    id: 18,
    name: "Margherita Pizza",
    price: 14,
    category: "Pizza",
    image: "🍕",
  },
  {
    id: 19,
    name: "Spaghetti Carbonara",
    price: 13,
    category: "Pasta",
    image: "🍝",
  },
  {
    id: 20,
    name: "Penne Arrabbiata",
    price: 12,
    category: "Pasta",
    image: "🍝",
  },
  {
    id: 21,
    name: "Caesar Salad",
    price: 9,
    category: "Salads",
    image: "🥗",
  },
  {
    id: 22,
    name: "Greek Salad",
    price: 10,
    category: "Salads",
    image: "🥗",
  },
  // Sweet Treats items
  {
    id: 23,
    name: "Vanilla Ice Cream",
    price: 5,
    category: "Ice Cream",
    image: "🍦",
  },
  {
    id: 24,
    name: "Chocolate Ice Cream",
    price: 5,
    category: "Ice Cream",
    image: "🍦",
  },
  {
    id: 25,
    name: "Chocolate Cake",
    price: 7,
    category: "Desserts",
    image: "🍰",
  },
  {
    id: 26,
    name: "Cheesecake",
    price: 8,
    category: "Desserts",
    image: "🍰",
  },
  {
    id: 27,
    name: "Candy Mix",
    price: 4,
    category: "Candy",
    image: "🍬",
  },
  {
    id: 28,
    name: "Lollipops",
    price: 3,
    category: "Candy",
    image: "🍭",
  },
  // Coffee Corner items
  {
    id: 29,
    name: "Espresso",
    price: 4,
    category: "Coffee",
    image: "☕",
  },
  {
    id: 30,
    name: "Cappuccino",
    price: 5,
    category: "Coffee",
    image: "☕",
  },
  {
    id: 31,
    name: "Green Tea",
    price: 4,
    category: "Tea",
    image: "🍵",
  },
  {
    id: 32,
    name: "Black Tea",
    price: 4,
    category: "Tea",
    image: "🍵",
  },
  {
    id: 33,
    name: "Croissant",
    price: 5,
    category: "Pastries",
    image: "🥐",
  },
  {
    id: 34,
    name: "Muffin",
    price: 4,
    category: "Pastries",
    image: "🧁",
  },
];

